# Generated by Django 6.0.1 on 2026-01-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_status_en',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Забронирован', 'Забронирован'), ('Свободный', 'Свободный')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_status_ru',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Забронирован', 'Забронирован'), ('Свободный', 'Свободный')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_en',
            field=models.CharField(choices=[('Люкс', 'Люкс'), ('Полулюкс', 'Полулюкс'), ('Семейный', 'Семейный'), ('Эконом', 'Эконом'), ('Одноместный', 'Одноместный'), ('Одноместный', 'Одноместный'), ('Трехместный', 'Трехместный'), ('Четырехместный', 'Четырехместный')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_ru',
            field=models.CharField(choices=[('Люкс', 'Люкс'), ('Полулюкс', 'Полулюкс'), ('Семейный', 'Семейный'), ('Эконом', 'Эконом'), ('Одноместный', 'Одноместный'), ('Одноместный', 'Одноместный'), ('Трехместный', 'Трехместный'), ('Четырехместный', 'Четырехместный')], max_length=20, null=True),
        ),
    ]
